

[package]
name = "git_client"
version = "0.1.0"
authors = ["Abha Ingle", "Nruthya Kadam", "Rutuja Talekar", "Sushruth Harsha"]
edition = "2021"

[dependencies]
clap = "2.33.0"
rust-crypto = "0.2.36"
regex = "1"
lazy_static = "1.3.0"
git2 = "0.13"


